### ISSUE TITLE
wget downloading all versions in Slackware directory 

### ISSUE THREAD

**Issue by Practicalbutterfly5** [ivan-hc/AM-application-manager#4] opened 2021-12-27 02:40 UTC
I installed chromium i686 using the script. It had 2 version in Slackware directory and it downloaded both. Can something be done to prevent this and download only the latest version?

**Comment by ivan-hc** [comment] 2021-12-27 04:10
I have temporarily removed the file, I will work on resolving the problem as soon as possible.

Chromium installation is a process that I plan to extract from the main source, rather than having to rely on Slackware.

**Comment by ivan-hc** [comment] 2021-12-27 04:43
in the meantime I've uploaded the more recent Chromium Snapshot edition, this version should work on 32bit systems too, let me know https://github.com/ivan-hc/AM-application-manager/blob/main/programs/i686/chromium-latest

**Comment by ivan-hc** [comment] 2021-12-27 05:04
OK, this time the problem should be solved, here is the new script for chromium stable (32 bit) https://github.com/ivan-hc/AM-application-manager/blob/main/programs/i686/chromium

 `sudo am -i chromium`

I've only tested the download (lines 15 and 38), but everything should work well.

**Comment by ivan-hc** [comment] 2021-12-27 05:20
I've converted the same script from 32bit to 64bit and I've successfully installed Chromium on my x64 machine using this script https://github.com/ivan-hc/AM-application-manager/blob/main/programs/x86_64/chromium

The main difference is x86_64 instead of i586 and the files are located in /lib64 instead of /lib

Can you confirm that everything works fine for you?

**Comment by Practicalbutterfly5** [comment] 2021-12-27 13:43
> OK, this time the problem should be solved, here is the new script for chromium stable (32 bit) https://github.com/ivan-hc/AM-application-manager/blob/main/programs/i686/chromium
> 
> `sudo am -i chromium`
> 
> I've only tested the download (lines 15 and 38), but everything should work well.

This works well and I can open chromium on archlinux32. But I have a probed with chromium here. I can’t load any websites in this chromium, and it just stays on new tab. Perhaps it is just my system.

**Comment by Practicalbutterfly5** [comment] 2021-12-27 14:03
Edit: seems like running chromium with ‘—no-sandbox’ works, but running without sandboxing is important for security

**Comment by ivan-hc** [comment] 2021-12-27 14:36
this is really strange, the version for x86_64 works realy well with the sandbox, and normally if I start `chromium --no-sandbox` a message of risks appear on the top bar of my chromium. 

PS: I've installed the 32bit version on Debian 11 for i686 right now and the browser wont start. Maybe is just this version that wont work. The same is for `chromium-latest`, that is not the latest version but the old 51 (download link at https://download-chromium.appspot.com/dl/Linux?type=snapshots ), so I have to remove it.

**Comment by ivan-hc** [comment] 2021-12-27 14:50
Just tested also `chromium-ungoogled` for i586 from Slackware on Debian 11 i686, the browser wont work, "instruction is not allowed", with or without a sandbox.

**Comment by ivan-hc** [comment] 2021-12-27 15:04
we should work on an alternative solution, the source itself is good for x86_64, but not for i686. I will look for a new source today, but I can't promise you any success, being Chromium one of the more difficult software to find in the internet. To compile a stable version is needed a lot of work too, that's why on Debian they have a lot of problems in compiling the latest stable version (now Debian has Chromium 93, Arch, Slackware and other distributions have Chromium 96 instead. I will do my best.

**Comment by ivan-hc** [comment] 2021-12-27 15:13
About `chromium-latest`, the version for x86 is no more developed and you can download the last build (382086) of 5 years ago here https://download-chromium.appspot.com (if you use a x64 system, the user agent will show the last build, in this moment is 954191 | Updated 6 minutes ago).

**Comment by Practicalbutterfly5** [comment] 2021-12-27 15:25
What version are you trying? I am able to successfully launch [chromium 96.0.4664.110-i586](http://www.slackware.com/~alien/slackbuilds/chromium/pkg/current/chromium-96.0.4664.110-i586-1alien.txz) with --no-sandbox on i686 archlinux32(fresh install)

**Comment by ivan-hc** [comment] 2021-12-27 15:41
> What version are you trying? I am able to successfully launch chromium 96.0.4664.110-i586 with --no-sandbox on i686 archlinux32(fresh install)
I'm not able to launch any Chromium version on Debian 11 i686 instead, and you have to launch it without a sandbox. In both cases, the program is buggy and doesn't work as expected.

**Comment by ivan-hc** [comment] 2021-12-27 16:41
OK, is seems to be a bug that affects all the chromium-based browsers since v94, Ive found this by searching the error message it shows me:
https://www.google.com/search?channel=crow5&client=firefox-b-d&q=ERROR%3Ascoped_ptrace_attacg.cc
I want to continue investigating .

**Comment by ivan-hc** [comment] 2021-12-27 17:40
OK, it seems to be a problem related to the newer releases of Chromium and its derivatives since v92, here are some error messages I can get when I launch `chromium` or `chromium --no-sandbox` from the terminal:

       `ERROR:scoped_ptrace_attacg.cc(37) process not stopped 
        ERROR:scoped_ptrace_attacg.cc(27) ptrace operation not permitted`

Debian 11 i686, Systemd 247, the laptop is an old ASUS Z9200VM Intel Pentium M Processor 740 (born with Windows XP).

Everything works well, except Chromium.

Can you share the ERROR messages when you launch the same two commands from the terminal from your PC?

**Comment by Practicalbutterfly5** [comment] 2021-12-27 18:05
<details>
<summary>Command line output of chromium `--no-sandbox` (able to browse with no problem)</summary>
<br>

`[3936:3936:1227/231926.520018:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[3936:3936:1227/231926.560480:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[3936:3936:1227/231926.560983:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[3936:3936:1227/231926.561307:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3936:3936:1227/231926.591707:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Intel or NVIDIA OpenGL ES drivers are not supported.
[3936:3936:1227/231926.592013:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Intel or NVIDIA OpenGL ES drivers are not supported.
[3936:3936:1227/231926.592251:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3936:3936:1227/231926.592452:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[3936:3936:1227/231926.948510:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[3982:3982:1227/231932.120668:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[3982:3982:1227/231932.121480:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[3982:3982:1227/231932.121878:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[3982:3982:1227/231932.122177:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3982:3982:1227/231932.152505:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Intel or NVIDIA OpenGL ES drivers are not supported.
[3982:3982:1227/231932.153001:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Intel or NVIDIA OpenGL ES drivers are not supported.
[3982:3982:1227/231932.153283:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3982:3982:1227/231932.153557:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[3982:3982:1227/231932.171962:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[3912:4047:1227/231932.805422:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[3912:4047:1227/231932.806533:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[3912:4047:1227/231932.807632:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[4048:4048:1227/231932.910625:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[4048:4048:1227/231932.911201:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[4048:4048:1227/231932.911466:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[4048:4048:1227/231932.911626:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[4048:4048:1227/231932.931307:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Intel or NVIDIA OpenGL ES drivers are not supported.
[4048:4048:1227/231932.931853:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Intel or NVIDIA OpenGL ES drivers are not supported.
[4048:4048:1227/231932.932150:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[4048:4048:1227/231932.932391:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[4048:4048:1227/231932.952225:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[4062:4062:1227/231933.490746:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[4062:4062:1227/231933.491428:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[4062:4062:1227/231933.491773:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[4062:4062:1227/231933.491932:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[4062:4062:1227/231933.514056:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Intel or NVIDIA OpenGL ES drivers are not supported.
[4062:4062:1227/231933.515890:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Intel or NVIDIA OpenGL ES drivers are not supported.
[4062:4062:1227/231933.516405:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[4062:4062:1227/231933.520916:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[4062:4062:1227/231933.541646:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[4069:4069:1227/231933.782010:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[4069:4069:1227/231933.782739:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[4069:4069:1227/231933.783114:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[4069:4069:1227/231933.783272:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[4069:4069:1227/231933.802042:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Intel or NVIDIA OpenGL ES drivers are not supported.
[4069:4069:1227/231933.802336:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Intel or NVIDIA OpenGL ES drivers are not supported.
[4069:4069:1227/231933.802582:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[4069:4069:1227/231933.802790:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[4069:4069:1227/231933.826286:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[4076:4076:1227/231936.125069:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[3912:3923:1227/231938.362777:ERROR:chrome_browser_main_extra_parts_metrics.cc(226)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[3912:3923:1227/231938.362909:ERROR:chrome_browser_main_extra_parts_metrics.cc(229)] crbug.com/1216328: Checking Bluetooth availability ended.
[3912:3923:1227/231938.362979:ERROR:chrome_browser_main_extra_parts_metrics.cc(232)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[3912:3923:1227/231938.560444:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status ended.`
</details>

<details>
<summary>Command line output of chromium (stuck on New Page and not responding)</summary>
<br>

`[4831:4831:1227/232753.123480:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[4831:4831:1227/232753.150713:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[4831:4831:1227/232753.161939:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[4831:4831:1227/232753.171873:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[4831:4831:1227/232753.374222:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Intel or NVIDIA OpenGL ES drivers are not supported.
[4831:4831:1227/232753.381016:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Intel or NVIDIA OpenGL ES drivers are not supported.
[4831:4831:1227/232753.382661:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[4831:4831:1227/232753.404190:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[4831:4831:1227/232753.520726:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[4799:4879:1227/232756.410519:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[4799:4879:1227/232756.439542:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[4799:4879:1227/232756.444264:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[4872:4872:1227/232756.776800:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[4872:4872:1227/232756.947632:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[4872:4872:1227/232756.954413:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[4872:4872:1227/232756.995635:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[4872:4872:1227/232757.420693:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Intel or NVIDIA OpenGL ES drivers are not supported.
[4872:4872:1227/232757.424426:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Intel or NVIDIA OpenGL ES drivers are not supported.
[4872:4872:1227/232757.432680:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[4872:4872:1227/232757.436266:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[4872:4872:1227/232757.598537:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[4929:4929:1227/232758.226743:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[4799:4814:1227/232806.913899:ERROR:chrome_browser_main_extra_parts_metrics.cc(226)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[4799:4814:1227/232806.914040:ERROR:chrome_browser_main_extra_parts_metrics.cc(229)] crbug.com/1216328: Checking Bluetooth availability ended.
[4799:4814:1227/232806.914112:ERROR:chrome_browser_main_extra_parts_metrics.cc(232)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[4799:4814:1227/232808.047575:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status ended.`
</details>

**Comment by ivan-hc** [comment] 2021-12-27 19:03
> Command line output of chromium `--no-sandbox` (able to browse with no problem)
> Command line output of chromium (stuck on New Page and not responding)
> 
> `/opt/chromium/chromium --version` `Chromium 96.0.4664.110 `

I've installed a VM of Debian 11 i686 right now and I can reproduce the same error messages.

Chromium only works with the `--no-sandbox` option. I had more problems with the old laptop.

In general, the problem is running any chromium-based browser on a 32bit architecture. The more is old the hardware, the more we will have troubles. 

From what I understand, Chromium expects to be able to take advantage of full hardware acceleration, but unable to find the necessary components, it crashes. I tried to disable hardware acceleration, but the problem still exists.

I need to see if the base system needs kernel headers or additional drivers.

**Comment by ivan-hc** [comment] 2021-12-27 20:29
Well, now the whole scenario is clear to me:

On [Arch Linux at 32bit the Chromium version is the same](https://archlinux32.org/packages/?q=chromium) as [Debian 11  32bit](https://packages.debian.org/bullseye/chromium), i.e. 90, while [in the Debian Unstable repositories the version is 93](https://packages.debian.org/sid/chromium), as the team is working to ensure the same version for all supported architectures . [Other distributions](https://repology.org/project/chromium/versions) have dropped support for the 32bit architecture, which is why they can afford to work on the newer versions (currently Chromium 96).
[As for Slackware, I think that the availability of the two packages in the repository](http://www.slackware.com/~alien/slackbuilds/chromium/pkg/current/) (at [the opening of this "issue"](https://github.com/ivan-hc/AM-application-manager/issues/4#issue-1088917663)) is due to the fact that the 32bit version 96 does not work well on Slackware, so the developer wanted to make the version also available 89 for 32bit Slackware Current, not 64bit Slackware Current.

So [the problem is definitely related to the compatibility between Chromium (and its derivatives) with the 32bit architecture for Linux](https://github.com/ivan-hc/AM-application-manager/issues/4#issuecomment-1001649883).

We can't appeal to none, as [Chromium is just an experimental developer version of Google Chrome](https://www.chromium.org/), and therefore no official build is released.
[Whoever distributes Chromium Stable is certainly an external developer](https://chromium.woolyss.com/), and does it for their own Linux distribution of origin, it is certainly not Google that guarantees its availability. The fact that there are no Google Chrome builds available for the 32bit architecture is another proof that I am right.

So if we want the latest Stable version of Chromium for 32bit architecture we have to rely on the one made available in our distribution's repositories for 32bit.

This version distributed by "AM" is actually the one from Slackware, so I will try to replace it with the previous one made available for Slackware, if you really want a 100% working version, and yo you want.

Otherwise we would have to build a 32-bit version by ourselves and that can fully support all the limitations of the 32-bit architecture today, at the end of 2021, ant as I've already said, this is not an easy task for anyone want to distribute the official Chromium Stable release.

Anyone who wants to use Chromium 96 on 32bit architecture today will not have an easy time, and if it really works, they will be forced to run it with the `--no-sandbox` option, for now.

I could not find other reasons, current browsers focus a lot on hardware acceleration to reproduce multimedia content that without compatible codecs they could never reproduce.

We can therefore consider this issue closed.

**Closed by ivan-hc** 2021-12-27 20:29 UTC
Labels: bug, wontfix

**Comment by ivan-hc** [comment] 2022-02-17 05:17
hi, I have replaced the version available from the Slackware (i586) repository with the one from Ubuntu Bionic (i386, still supported until 2023). No issues here. You can check the changes here:
https://github.com/ivan-hc/AM-application-manager/commit/0a43857d428cfd2f543c196ffbd4046cbaca0f45
